add_newline = true
command_timeout = 200
format = "[$directory$git_branch]($style)$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[→](bold #FFAB91)"

[directory]
truncation_length = 2
truncate_to_repo = false
repo_root_style = "bold cyan"

[git_branch]
format = "[$branch]($style) "
style = "bold"

